import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import React from 'react';

const inter = Inter({ subsets: ['latin'] });

type Props = {
  params: {
    id: string;
  };
};

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const baseUrl = process.env.NEXT_PUBLIC_BASE_URL;
  const startPath = params.id || '';
  const startUrl = `${baseUrl}api/manifest?start_url=${startPath}`;

  return {
    title: 'Next.js PWA Template',
    description: 'Generated by create next app',
    manifest: startUrl,
  };
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <head>
        <link rel='apple-touch-icon' href='/icon.png' />
        <meta name='theme-color' content='#ffffff' />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
